/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_8 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] sum,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [8:0] sum1;
  
  integer i;
  
  always @* begin
    n = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        sum1 = a + b;
      end
      2'h1: begin
        sum1 = a - b;
        n = sum1[7+0-:1];
        if (sum1[7+0-:1] == 1'h1) begin
          for (i = 1'h0; i < 4'h8; i = i + 1) begin
            sum1[(i)*1+0-:1] = sum1[(i)*1+0-:1] + 1'h1;
          end
          sum1 = sum1 + 1'h1;
        end
      end
      2'h2: begin
        sum1 = a * b;
      end
      2'h3: begin
        sum1 = a - (a / b * b);
      end
      default: begin
        sum1 = a + b;
      end
    endcase
    sum = sum1[0+7-:8];
    z = (~|sum1);
    v = (a[7+0-:1] & b[7+0-:1] & (~sum1[7+0-:1])) | ((~a[7+0-:1]) & (~b[7+0-:1]) & sum1[7+0-:1]);
  end
endmodule
